server:
  port: 8081
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/raylelo?useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: welcome
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: true